In [2]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
df = pd.read_csv("student_data.csv")
df.head()

   Age  Marks  Study_Hours  Pass
0   21   94.9          9.4     1
1   18   81.9          8.9     1
2   27   77.1          6.0     1
3   29   99.6          9.2     1
4   25   33.5          0.9     0

In [4]:
print(df.shape)
df.info()
df.describe()

(100, 4)
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          100 non-null    int64
 1   Marks        100 non-null    float64
 2   Study_Hours  100 non-null    float64
 3   Pass         100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

              Age       Marks  Study_Hours        Pass
count  100.000000  100.000000   100.000000  100.000000
mean    22.270000   59.200000     4.806000    0.720000
std      4.251809   24.361283     2.990889    0.451261
min     15.000000   14.200000     0.100000    0.000000
25%     18.750000   36.500000     2.375000    0.000000
50%     22.000000   58.300000     4.500000    1.000000
75%     26.000000   80.850000     7.700000    1.000000
max     29.000000  100.000000     9.900000    1.000000

In [5]:
X = df[["Age",'Marks','Study_Hours']]
Y = df["Pass"]
print(X.head())
print(Y.head())

   Age  Marks  Study_Hours
0   21   94.9          9.4
1   18   81.9          8.9
2   27   77.1          6.0
3   29   99.6          9.2
4   25   33.5          0.9
0    1
1    1
2    1
3    1
4    0
Name: Pass, dtype: int64

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,test_size=0.2,random_state=42
)

print(X_train.shape)
print(X_test.shape)

(80, 3)
(20, 3)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = Sequential() # Generates a sequential pipeline of input layer then hidden layers and then output layer.

# Here input - 8 neurons - hidden layer1 (4 neurons)- hidden layer2 - output1
# If there is a larger dataset then we can start from 64,32,16,8,4,2,1 neurons sequentially and accordingly will be the hidden layers and at last will be the output.
model.add(Dense(8,
                activation="relu",
                input_shape=(3,))) # 3 columns as input

model.add(Dense(4,
                activation='relu'))

model.add(Dense(1,
                activation='sigmoid'))

In [13]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [30]:
history = model.fit(
    X_train,
    Y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.2   # 20% of training data used for validation
)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7188 - loss: 0.6761 - val_accuracy: 0.8125 - val_loss: 0.6727
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6739 - val_accuracy: 0.8125 - val_loss: 0.6696
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6716 - val_accuracy: 0.8125 - val_loss: 0.6664
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6692 - val_accuracy: 0.8125 - val_loss: 0.6632
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6670 - val_accuracy: 0.8125 - val_loss: 0.6596
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6642 - val_accuracy: 0.8125 - val_loss: 0.6559
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.6617 - val_accuracy: 0.8125 - val_loss: 0.6515
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.6589 - val_accuracy: 0.8125 - val_loss: 0.6470
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.6555 - val_accuracy: 0.8125 - val_loss: 0.6426
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.6520 - val_accuracy: 0.8125 - val_loss: 0.6381
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6485 - val_accuracy: 0.8125 - val_loss: 0.6333
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.6447 - val_accuracy: 0.8125 - val_loss: 0.6285
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6408 - val_accuracy: 0.8125 - val_loss: 0.6231
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6368 - val_accuracy: 0.8125 - val_loss: 0.6171
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6321 - val_accuracy: 0.8125 - val_loss: 0.6110
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.6271 - val_accuracy: 0.8125 - val_loss: 0.6047
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6226 - val_accuracy: 0.8125 - val_loss: 0.5977
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6173 - val_accuracy: 0.8125 - val_loss: 0.5904
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6114 - val_accuracy: 0.8125 - val_loss: 0.5831
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6060 - val_accuracy: 0.8125 - val_loss: 0.5754
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.6000 - val_accuracy: 0.8125 - val_loss: 0.5670
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5945 - val_accuracy: 0.8125 - val_loss: 0.5585
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7188 - loss: 0.5877 - val_accuracy: 0.8125 - val_loss: 0.5497
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.5814 - val_accuracy: 0.8125 - val_loss: 0.5407
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5750 - val_accuracy: 0.8125 - val_loss: 0.5314
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5682 - val_accuracy: 0.8125 - val_loss: 0.5222
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5613 - val_accuracy: 0.8125 - val_loss: 0.5129
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5545 - val_accuracy: 0.8125 - val_loss: 0.5036
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5478 - val_accuracy: 0.8125 - val_loss: 0.4934
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5407 - val_accuracy: 0.8125 - val_loss: 0.4834
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5341 - val_accuracy: 0.8125 - val_loss: 0.4735
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5268 - val_accuracy: 0.8125 - val_loss: 0.4643
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5202 - val_accuracy: 0.8125 - val_loss: 0.4544
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5135 - val_accuracy: 0.8125 - val_loss: 0.4446
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5062 - val_accuracy: 0.8125 - val_loss: 0.4354
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4994 - val_accuracy: 0.8125 - val_loss: 0.4265
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7188 - loss: 0.4926 - val_accuracy: 0.8125 - val_loss: 0.4177
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4858 - val_accuracy: 0.8125 - val_loss: 0.4093
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4799 - val_accuracy: 0.8125 - val_loss: 0.4005
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4732 - val_accuracy: 0.8125 - val_loss: 0.3924
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4672 - val_accuracy: 0.8125 - val_loss: 0.3842
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4611 - val_accuracy: 0.8125 - val_loss: 0.3763
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4552 - val_accuracy: 0.8125 - val_loss: 0.3686
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4495 - val_accuracy: 0.8125 - val_loss: 0.3609
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4441 - val_accuracy: 0.8125 - val_loss: 0.3539
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4387 - val_accuracy: 0.8125 - val_loss: 0.3471
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4338 - val_accuracy: 0.8125 - val_loss: 0.3408
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4286 - val_accuracy: 0.8125 - val_loss: 0.3350
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4240 - val_accuracy: 0.8125 - val_loss: 0.3287
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.4191 - val_accuracy: 0.8125 - val_loss: 0.3225

In [32]:
loss, accuracy = model.evaluate(X_test, Y_test)

print("Loss :", loss)

print("Accuracy :", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6500 - loss: 0.4782
Loss : 0.4781729578971863
Accuracy : 0.6499999761581421

In [33]:
prediction = model.predict(X_test)

prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

array([[0.6330855 ],
       [0.57458586],
       [0.6407364 ],
       [0.8462282 ],
       [0.8742559 ],
       [0.8804727 ],
       [0.7504051 ],
       [0.56350195],
       [0.7805464 ],
       [0.9001725 ],
       [0.85190487],
       [0.6350044 ],
       [0.7401389 ],
       [0.6397892 ],
       [0.73396766],
       [0.56350195],
       [0.56350195],
       [0.81084096],
       [0.6429143 ],
       [0.56350195]], dtype=float32)

In [ ]:
new_student = [[22,85,7]]

new_student = scaler.transform(new_student)

result = model.predict(new_student)

if result > 0.5:
    print("Pass")
else:
    print("Fail")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
Pass

C:\Users\Priyanshu\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(