In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [4]:
df = pd.read_csv("loan_data.csv")
df.head()

   Age  Income       Education Loan_Approved
0   25     Low        Graduate            No
1   32    High   Post-Graduate           Yes
2   28  Medium        Graduate           Yes
3   45    High        Graduate           Yes
4   22     Low  Under-Graduate            No

In [5]:
df.columns

Index(['Age', 'Income', 'Education', 'Loan_Approved'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            100 non-null    int64
 1   Income         100 non-null    str
 2   Education      100 non-null    str
 3   Loan_Approved  100 non-null    str
dtypes: int64(1), str(3)
memory usage: 3.3 KB

In [7]:
df.describe()

              Age
count  100.000000
mean    35.440000
std      9.532846
min     21.000000
25%     27.000000
50%     34.500000
75%     43.250000
max     55.000000

In [11]:
X = df[["Income","Education"]]
Y = df["Loan_Approved"]

In [13]:
encoder = OneHotEncoder()
X = encoder.fit_transform(X).toarray()

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,test_size=20,random_state=42
)

In [15]:
model = DecisionTreeClassifier(criterion = "gini")

In [16]:
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [17]:
def predict_loan(income,education):

    new_data = pd.DataFrame({
        "Income" : [income],
        "Education" : [education]
    })

    new_data = encoder.transform(new_data).toarray()

    result = model.predict(new_data)
    
    if result[0] == "Yes":
        print("Loan Approved")
    else:
        print("Loan Not Approved")

In [22]:
predict_loan("High","Post-Graduate")

Loan Approved

In [ ]:
s = "Hello"
s = "Hello1"
s1 = "xyz"
s2 = "xyz"
print(s)
print(s1)
print(s2)
print(id(s))
print(id(s1) is id(s2))
print(id(s1))
print(id(s2))

Hello1
xyz
xyzz
2038349967792
False
2038349963856
2038349964720